# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "48c0fb286b75d656dbb93fb019e253ea"
name = "spresso-test-app"
application_url = "https://floyd-obtain-moore-synopsis.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "spresso-test-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products"

[auth]
redirect_urls = [
  "https://floyd-obtain-moore-synopsis.trycloudflare.com/auth/callback",
  "https://floyd-obtain-moore-synopsis.trycloudflare.com/auth/shopify/callback",
  "https://floyd-obtain-moore-synopsis.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
